### ISSUE TITLE
[mpdf] Aufwandschätzung der JATS - HTML Konvertierung

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#1]
Die Ausgabe der XSLT style-sheet (XML->HTML)  soll überprüft werden, um zu schätzen wie viel Aufwand benötigt wird,  damit eine mpdf  input html generiert werden kann.
https://github.com/ncbi/JATSPreviewStylesheets/tree/master/xslt/main/jats-html.xsl
Eine Valide JATS-XML is im Anhang (in txt weil github  xml als Anhang nicht zulässt)
[43-69-209-1-10-20150717.txt](https://github.com/withanage/mpt/files/25228/43-69-209-1-10-20150717.txt)

**Comment by kadowa** [comment]
Für die Beispieldatei wird mit dem JATS-Stylesheet valides HTML erzeugt, aus der sich eine PDF generieren lässt.
