### ISSUE TITLE
Footnotes/Citations

### ISSUE THREAD

**Issue by kadowa** [withanage/mpt#12]
Wenn ich DOCX mit meTypeset nach XML konvertiere (ein beliebiges Habenstein-Kapitel, meTypeset einfach out of the box), werden aus als Fußnoten formatierte Zitationen [\<fn\>](http://jats.nlm.nih.gov/archiving/tag-library/1.1d2/element/fn.html)-Elemente, die als [\<fn-group\>](http://jats.nlm.nih.gov/archiving/tag-library/1.1d2/element/fn-group.html) organisiert sind. In den vorhandenen XML-Dateien ist es eine [\<ref-list\>](http://jats.nlm.nih.gov/archiving/tag-library/1.1d2/element/ref-list.html) mit [\<ref\>](http://jats.nlm.nih.gov/archiving/tag-library/1.1d2/element/ref.html)-Elementen , die [\<element-citation\>](http://jats.nlm.nih.gov/archiving/tag-library/1.1d2/element/element-citation.html)-Elemente enthalten. Was ist der Unterschied bzw. was hast du anders gemacht, @withanage? Und was wollen wir am Ende tatsächlich haben?

**Comment by withanage** [comment]
@kadowa 
fn-group steht für fußnoten, ref-list stehtf für Referenzen. Wir brauchen die beide.
In Habenstein haben wir nur fußnoten, die als Referenzen in xml stehen.
Wir brauchen die beide.
[Sander_Introduction_16.09.docx](https://github.com/withanage/mpt/files/36866/Sander_Introduction_16.09.docx)

z.B. Die Datei generiert mit  metypeset beide Referenzen und Fussnoten.
