### ISSUE TITLE
[mpdf] Footnote placement

### ISSUE THREAD

**Issue by kadowa** [withanage/mpt#13]
Footnotes appear per default at the end of an article, not on the page they are referenced. Since I suspect that we want the latter behaviour (at least that's how they are styled in the InDesign version of the Habenstein book), find out, whether and how this is possible with mPDF – so far I have found no resources on this particular topic –, or if we need to consider a different tool ([Prince](http://www.princexml.com/download/) seems to have this option, see [this example](https://github.com/rachelandrew/css-for-print)).

**Comment by withanage** [comment]
yes,  mpdf should  have the ability (if not, we have to let it)  or otherwise  "Prince"  is  also a option always. But then pdfa support should be tested. The license is expensive, but  have a look.

**Comment by kadowa** [comment]
Looks like there is no option to place footnotes on the page they are referenced on with mPDF (see [this discussion](http://www.mpdf1.com/forum/discussion/871) in the mPDF Forum). There is a way to handle [footnotes in CSS ](http://www.w3.org/TR/css-gcpm-3/#footnotes), but it's not included in the [list of CSS supported by MPDF](http://mpdf1.com/manual/index.php?tid=34).

Prince seems to support [PDF/A-1b](http://www.princexml.com/forum/topic/1136/how-do-i-create-a-pdf-a-1a-compliant-pdf-using-prince-xml), but the price is comparable to the Antenna House Formatter.

**Comment by withanage** [comment]
Antenna generiert  das PDF  html+css -> fo -> pdf
Macht der prince renderer  ohne ein fo  zwischenschritt?

**Comment by kadowa** [comment]
Prince macht HTML -> PDF, mit FO hat das nichts zu tun.

**Comment by withanage** [comment]
Kannst Du  2  test- shell skripte für prince und antenna in xml2pdf integrieren., wie du für mpdf1 schon gemacht hast.
