### ISSUE TITLE
2 Spaltige   Layouts 

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#14]
JATS  und das Buch DTD von NLM  hat keine  column-break tag.  Es wird vorgeschlagen ein <target  specific-use="column-break"> zu verwenden.
Es ist riskant  line-breaks direkt  einzutragen. Am besten sollte  in typesetter konfiguriert werden,ob der output 2-spaltig ist und fo sollte selber um die Seiten Trennung kümmern.
Gibt ein Beispiel beim AH 
Ergebnis
http://www.antennahouse.com/antenna1/wp-content/uploads/2015/07/region-2.pdf
Input FO
http://www.antennahouse.com/antenna1/wp-content/uploads/2015/07/region-2.zip

**Comment by withanage** [comment]
@fkrb  thanks for the commit.

**Comment by fkrb** [comment]
Sehe ich auch so. Layout-Anweisungen sollten als XSL-FO/CSS-Template im Typesetter hinterlegt werden. Es wäre gut, wenn man mehrere Templates in MPT hinterlegen könnte (z. B. für verschiedene Buchformate oder spezifische Reihen-Layouts). In MPT könnte man dann einer Publikation ein Layout-Template zuweisen, mit dem es formatiert werden soll.

**Comment by withanage** [comment]
Ja, das Skript  
https://github.com/withanage/mpt/blob/master/static/tools/runTest.py
von @kadowa  ist konfigurierbar.

@kadowa  : wir  sollten  in wiki dokumentieren wie man das Skript  konfiguriert  und gegenbenfalls das Skript erweitern.

**Comment by kadowa** [comment]
Es gibt eine [Beispiel-Config-Datei](https://github.com/withanage/mpt/blob/master/static/tools/test.cfg), in der die einzelnen Konfigurationsoptionen gelistet sind. Die zu verwendenden Stylesheets lassen sich hier konfigurieren: https://github.com/withanage/mpt/blob/master/static/tools/test.cfg#L36-L50, z.B.

```
[stylesheets]

; XML2HTML transformation
xslt_html=/workspace/mpt/static/stylesheets/jats-html.xsl

; XML2FO transformation
xslt_fo=/workspace/mpt/static/stylesheets/jats-xslfo.xsl

; CSS styles
css=/workspace/mpt/static/stylesheets/custom.css
```

**Comment by withanage** [comment]
Vielen Dank @kadowa. kannst du es in wiki eintragen?
Am besten hier  direkt  (nicht nur in pages)
https://github.com/withanage/mpt/wiki
und hier als Unterpunkt - Test Confifurations 
https://github.com/withanage/mpt/wiki/doc2pdf:-Tests
Mir fällt auch auf einige WIKI Einträge  auf deutsch sind. Wiki sollten wir nur auf english schreiben.

**Comment by kadowa** [comment]
@withanage, alles auf eine Seite wird sehr unübersichtlich (vor allem zum Editieren ist das ein Alptraum). Habe für die Doku der Test-Suite eine [README.md](https://github.com/withanage/mpt/blob/master/static/tools/README.md) erstellt und alles auf der Wiki-Startseite verlinkt. Leider kann das Github-Wiki weder hierarchische Seiten noch automatische Inhaltsverzeichnisse, daher alles von Hand.

**Comment by kadowa** [comment]
Da die Wiki-Seiten auch in Markdown sind, hab ich die README auch noch direkt ins Wiki gestellt, https://github.com/withanage/mpt/wiki/doc2pdf:-Test-Suite.

**Comment by withanage** [comment]
@kadowa  Vielen Dank für die Änderugen . Ja ohne automatisches inhaltverzeihnis ist nicht optimal.

**Comment by AnjaKonopka** [comment]
Liebe alle,

ich verstehe nur Bahnhof. Kann mir das jemand so erkären, dass ich
annähernd verstehe, war ihr macht? Vielleicht in der nächsten OMP-Runde?

Liebe Grüße
Anja

----- Nachricht von Frank Krabbes <notifications@github.com> ---------
     Datum: Fri, 08 Jan 2016 01:21:26 -0800
       Von: Frank Krabbes <notifications@github.com>
Antwort an: withanage/mpt
<reply@reply.github.com>
   Betreff: Re: [mpt] 2 Spaltige   Layouts  (#14)
        An: withanage/mpt <mpt@noreply.github.com>

> Sehe ich auch so. Layout-Anweisungen sollten als XSL-FO/CSS-Template im
> Typesetter hinterlegt werden. Es wäre gut, wenn man mehrere Templates in
> MPT hinterlegen könnte (z. B. für verschiedene Buchformate oder
> spezifische Reihen-Layouts). In MPT könnte man dann einer Publikation
> ein Layout-Template zuweisen, mit dem es formatiert werden soll.
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       

----- Ende der Nachricht von Frank Krabbes <notifications@github.com> -----



Links:
------
[1] https://github.com/withanage/mpt/issues/14#issuecomment-169944306
  Anja Konopka
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel: +49 6221 542569
E-Mail: konopka@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de/

**Comment by withanage** [comment]
@AnjaKonopka  kommt ein Beitrag von @fkrb  in OMP Runde.

**Comment by withanage** [comment]
@kadowa  2-spaltige l layout tests, brauchen wir für prince und unter [tests](https://github.com/withanage/mpt/wiki/doc2pdf:-Tests) dokumentiert.

**Comment by withanage** [comment]
@kadowa  kann dieses gelöscht werden ?

**Comment by kadowa** [comment]
@fkrb, du hattest mir noch einige Punkte zu mehrspaltigen Layouts und Abbildungen/Floats geschickt. Hast du die schon alle mit AHF/FOP getestet? Wenn ja, könntest du das Ergebnis bei Gelegenheit in der Test-Tabelle ergänzen?
