### ISSUE TITLE
Zuordnung der Tests in Wiki

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#17]
@kadowa 
es ist sehr hilfreich
falls wir die Ergebnisse Dateien
https://github.com/withanage/mpt/tree/master/static/tests/misc/pdf

in wiki  verlinkt kriegen.
https://github.com/withanage/mpt/wiki/doc2pdf:-Tests

Dann können wir leicht jemand das Ergebnis zeigen, ohne zu navigieren.

**Comment by kadowa** [comment]
Ok, mache ich für Prince. Für die Negativ-Beispiele brauchen wir ja keine Verlinkung, oder?

**Comment by withanage** [comment]
klar, brauchen wir nicht.

**Comment by withanage** [comment]
bitte auch ah tests verlinken.
