### ISSUE TITLE
[prince] xml to pdf

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#19]
Unterstützt der prince   jats direkt ohne ein html zwischenschritt   ?
 http://www.princexml.com/samples/

**Comment by kadowa** [comment]
Ja, da Prince XML unterstützt. Dann benötigt man nur das entsprechende Stylesheet (https://github.com/withanage/mpt/blob/master/static/stylesheets/jpd.css).

Beispiel hier: https://github.com/withanage/mpt/blob/master/static/tests/misc/pdf/bmj_sample.prince.pdf.
