### ISSUE TITLE
post processer script

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#21]
Sollte in post-processor eingebaut werden, damit die interviews speaker geschnitten werden

(\<p>)(\s*)(\w+)(:)

**Comment by kadowa** [comment]
Ein grundsätzlicher Punkt: ich würde mehrere separate Skripts kombinieren, anstatt alles in eines zu packen, da dann je nach Bedarf ausgewählt werden kann, was an Post-Processing gebraucht wird. Für den Habenstein-Band haben wir ja z.B. keine Interviews. Bisher habe ich diese zwei (für Habenstein): https://github.com/withanage/mpt/tree/master/static/tools/scripts

**Comment by withanage** [comment]
ja,  am besten ist es, mit dem befehl
z.B. 
postporcess.py --endnote2footnotes  --cleancomments  meinxml
die skripte in der reihenfolge  aufgerufen wird.

**Comment by kadowa** [comment]
@withanage, ich verstehe leider den RE oben nicht. Was soll wo geschnitten werden?

In der XML sieht der Interview-Teil so aus:

```
        <p>
          <speech id="1">
            <speaker>Paul</speaker>
            <speaker>Interviewer</speaker>
            <speaker>Paul</speaker>
            <p>
              <xref ref-type="fn" rid="bibd2e58">1</xref>
            </p>
          </speech>
        </p>
        <p>
          <speech id="2">
            <speaker>Interviewer</speaker>
            <speaker>Paul</speaker>
            <p>
              <xref ref-type="fn" rid="bibd2e58">1</xref>
            </p>
          </speech>
        </p>
        <p>
          <speech id="3">
            <speaker>Paul</speaker>
            <p>
              <xref ref-type="fn" rid="bibd2e58">1</xref>
            </p>
          </speech>
        </p>
```
Allerdings fehlt der eigentliche Inhalt. Ist das Absicht oder schon nach Post-Processing?

**Comment by kadowa** [comment]
So sieht es in der PDF aus:
![interview](https://cloud.githubusercontent.com/assets/8066366/12611702/77622be2-c4ee-11e5-8430-919ee050f88e.png)

**Comment by withanage** [comment]
@kadowa  du scheinst bei dir eine alte xml zu haben.
hast du aktualisiert ?
alle diese 3 haben die Daten in <p>
https://github.com/withanage/mpt/tree/master/static/tests/sander/src/xml

**Comment by kadowa** [comment]
Ah ok, das war die XML, die du mir letzte Woche gemailt hast. Ich wusste nicht, dass die, die du commited hast, eine neuere Version ist.

**Comment by withanage** [comment]
@kadowa  gibt es was zu sehen mit sanderband oder ist es noch früh?

**Comment by kadowa** [comment]
Nein; ich bin zurzeit ziemlich mit den OMP-Portalen eingespannt und war zwischenzeitlich mehrfach krank.

**Comment by withanage** [comment]
ok, ich wollte nur wissen.  für  propyleaeum habe ich in tickets geantwortet. falls  was ganz drigend ist , lass mich wissen.
