### ISSUE TITLE
Renderer Perfomanz - Anzahl Bilder

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#22]
Wie gut kann die beide Renderer mit Bidldern umgehen?
Die Zeit ist nicht wichtig, aber ob die beide mit c 50, 100 Bilderen umgehen kann ?

**Comment by kadowa** [comment]
Hier https://github.com/withanage/mpt/blob/master/static/tests/misc/pdf/Images-FOP-Oxygen16.pdf und hier https://github.com/withanage/mpt/blob/master/static/tests/misc/pdf/images.prince.pdf haben wir mit einer größeren Anzahl Bilder getestet – bei beiden Renderern ohne Probleme. Reicht die Menge so aus, um die Frage zufriedenstellend zu beantworten?

**Comment by withanage** [comment]
die tests in beiden dateien reichen aus.
