### ISSUE TITLE
Unterschiedliche Paginierung für unterschiedliche Teile (Titelei, Kapitel, Anhang) 

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#24]
prince xml

**Comment by withanage** [comment]
Z.B. Römisch, Lateinisch im Wechsel.

**Comment by fkrb** [comment]
Auf jeden Fall kennt CSS PM verschiedene Zahlenformate auch für Seitenzahlen. Wenn man die paginierten Teile getrennt voneinander umbricht, sollte das problemlos funktionieren (mit "content: counter(page, lower-roman)" sollte ich das leicht testen lassen).

Ob es auch funktioniert, wenn man die Publikation in einem Durchgang komplett formatieren lassen will, kann ich aber nicht sagen.

**Comment by kadowa** [comment]
Ja, mit named pages funktioniert auch das: https://www.w3.org/TR/REC-CSS2/page.html#named-pages
