### ISSUE TITLE
Zeilenumbrüche 

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#3]
Word erlaubt die Kontrolle von Zeilenumbrüchen. Die Möglichkeit zur Kontrolle der Zeilenumbrüchen in PDF soll untersucht werden.

**Comment by withanage** [comment]
Für prince soll getestet werden.

**Comment by kadowa** [comment]
@withanage, kannst du das etwas konkreter ausformulieren? Was genau soll diese Kontrolle beinhalten? Das Verhinedern von Zeilenumbrüchen? Automatische Trennung?

**Comment by kadowa** [comment]
http://www.princexml.com/doc/properties/prince-linebreak-magic/

**Comment by withanage** [comment]
ja, ich meite das. sieht so aus, price kann das. Kannst Du dokumentieren  falls noch nicht gesehen und anschließend ticket schließen
