### ISSUE TITLE
Michl TODO

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#30]
-  [ ]  einige Kapilel mit Fußnoten in Überschrift wird nicht erkannt

**Comment by withanage** [comment]
@dingeborg @fkrb  und @ankosi 
Wir brauchen  Standard Großen für Überschriften. 
Template , HTML and PDF sollte genau festgelegt werden.  Mit mehr als 6  Ebenen  ist für Michel  sind die Bildschirme etwas eng.
@fkrb 
Welche Größen   werden für Michl in PDF  verwendet  ?
Habe ein kleines Test gemacht um das etwas zu verdeutlichen , bitte  um Vorschläge.
![screenshot from 2016-06-30 16 14 34](https://cloud.githubusercontent.com/assets/1921992/16491316/c77f6900-3edd-11e6-9a68-35063d8a765c.png)

**Comment by fkrb** [comment]
Liebe(r) @withanage, @ankosi, @dingeborg,

ich glaube, eine Standardisierung ist m. E. nur für HTML sinnvoll. Was 
den Platz in Darstellung rechts anbetrifft, können wir das halt nicht 
ändern. Die Überschriften im Word-Template zu standardisieren, ist 
schlecht möglich. Wir können zwar Überschriftengrößen bestimmen, aber 
das Template muss sowohl viele Ebenen beherrschen, als auch lesbar 
bleiben. Ich möchte vermeiden, dass die Überschrift 1 immer z. B. 72 
Punkt groß ist, weil wir 8 Ebenen unterstützen können.

Eine Standardisierung für PDF strebe ich ersteinmal nur für den 
FO-Umbruch an.

Liebe Grüße,

Frank


Am 30.06.2016 um 16:15 schrieb Dulip Withanage:
>
> @dingeborg <https://github.com/dingeborg> @fkrb 
> <https://github.com/fkrb> und @ankosi <https://github.com/ankosi>
> Wir brauchen Standard Großen für Überschriften.
> Template , HTML and PDF sollte genau festgelegt werden. Mit mehr als 6 
> Ebenen ist für Michel sind die Bildschirme etwas eng.
> @fkrb <https://github.com/fkrb>
> Welche Größen werden für Michl in PDF verwendet ?
> Habe ein kleines Test gemacht um das etwas zu verdeutlichen , bitte um 
> Vorschläge.
> screenshot from 2016-06-30 16 14 34 
> <https://cloud.githubusercontent.com/assets/1921992/16491316/c77f6900-3edd-11e6-9a68-35063d8a765c.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/withanage/mpt/issues/30#issuecomment-229671368>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AO_4PQ5aEHClp7eU7x1XcVXj8Lmu4-Seks5qQ8-VgaJpZM4Ixxaq>.
>

-- 
Frank Krabbes
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109
69117 Heidelberg

Tel: +49 (0)6221 542569
Fax: +49 (0)6221 542623

E-Mail: krabbes@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de

**Comment by withanage** [comment]
Lieber Frank,
ja, für html ist es unverzichtbar, da  ein einheitliches Layout  verwendet wird. 
@anskosi und ich  würden eher ab 4. Ebene in HTML erst gar nicht anzeigen , falls Michl das wünscht.
Mit circa 400 Pixel in einem Mobil-gerät  wird die Darstellung eh nicht akzeptabel, auch wenn man in Detail optimiert.

**Comment by dingeborg** [comment]
Lieber Dulip,
Anja übernimmt die HTML-Version von Michl... - ich habe eine andere 
Aufgabe... Daher setzt Du Dich wahrscheinlich am besten mit ihr zusammen...
Was die Überschriften angeht, so werden diese nur in den ersten 4 Ebenen 
im PDF tatsächlich unterschieden (Größe oder Schriftart/Schriftschnitt); 
danach wird die Überschrift nur noch durch die entsprechende 
Nummerierung gekennzeichnet...Ich kann Herrn Michl fragen, ob es für ihn 
in Ordnung ist, wenn in der HTML-Version nur die ersten 4 Ebenen 
seitlich angezeigt werden...
Lieben Gruß,
Dani

Am 01.07.2016 um 09:59 schrieb Dulip Withanage:

**Comment by withanage** [comment]
Liebe Daniela,
ja, das  mit 4 Überschriften denke ich, dass auch in Mobil-Geräten besser sichtbar wird. Frag bitte  ihm was er dazu hält.

**Comment by dingeborg** [comment]
Liebe Anja, lieber Dulip,
die Michl-Dateien sind jetzt durchgelaufen und sollten jetzt über Oxygen 
angezeigt werden...
Michl werde ich wegen der Überschriften-Struktur in der HTML-Ansicht 
fragen...
Lieben Gruß,
Dani

Am 04.07.2016 um 10:30 schrieb Dulip Withanage:
