### ISSUE TITLE
meTypeset Konvertierungsfehler

### ISSUE THREAD

**Issue by dingeborg** [withanage/mpt#31]
06_KapitelD_Michl_Kapitel3 verursacht bei der Konvertierung folgenden Fehler:

```
[Size Classifier] WARNING: size elements were disordered
[Size Classifier] Reverting to backup tree as size classification failed
Traceback (most recent call last):
  File "bin/meTypeset.py", line 252, in <module>
    main()
  File "bin/meTypeset.py", line 248, in main
    me_typeset_instance.run()
  File "bin/meTypeset.py", line 240, in run
    self.run_modules()
  File "bin/meTypeset.py", line 168, in run_modules
    SizeClassifier(self.gv).run()
  File "/usr/local/meTypeset/bin/sizeclassifier.py", line 555, in run
    manipulate.save_tree(tree)
  File "/usr/local/meTypeset/bin/teimanipulate.py", line 22, in save_tree
    tree.write(self.dom_temp_file, pretty_print=self.gv.settings.args['--prettytei'])
AttributeError: 'lxml.etree._Element' object has no attribute 'write'
```

**Comment by withanage** [comment]
@dingeborg  ist die datei noch aktuell in dem home verzeihnis hier ?

**Comment by dingeborg** [comment]
Lieber Dulip,
ja, die Datei dürfte ich nicht mehr geändert haben seitdem...
Lieben Gruß,
Dani

Am 23.06.2016 um 12:59 schrieb Dulip Withanage:

**Comment by withanage** [comment]
@dingeborg 
habe die Datei erstmal in dem output Ordner erzeugt, höchst wahrscheinlich ist die Überschriften-struktur nicht korrekt.   Bitte überprüfen und lass mich wissen.

**Comment by withanage** [comment]
@dingeborg  , habe  jetzt dein Home Verzeihnis  konfigurert,  Muss getestet werden und falls alle Probleme gelöst sind, bitte das ticket schließen.
