### ISSUE TITLE
meTypeset-Konvertierungsfehler: Block Quotes nicht erkannt

### ISSUE THREAD

**Issue by fkrb** [withanage/mpt#33]
Block Quotes werden als Paragraph (Jats: <p>) getaggt und nicht als Block Quote (Jats: <disp-quote>). 

Beispieldokument:  static/tests/word/SmallCaps_BlockQuotes.docx (Seite 1).

**Comment by withanage** [comment]
@fkrb  ist eingebaut und in serv21 kann getested werden.

**Comment by fkrb** [comment]
@withanage Funktioniert für das Testdokument. Danke. F.


Am 12.07.2016 um 15:08 schrieb Dulip Withanage:
>
> @fkrb <https://github.com/fkrb> ist eingebaut und in serv21 kann 
> getested werden.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/withanage/mpt/issues/33#issuecomment-232041675>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AO_4Pb0UGxqF3t7NYiFNkkC7p7w9tSdtks5qU5HMgaJpZM4I4Prl>.
>

-- 
Frank Krabbes
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109
69117 Heidelberg

Tel: +49 (0)6221 542569
Fax: +49 (0)6221 542623

E-Mail: krabbes@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de
