### ISSUE TITLE
meTypeset-Konvertierungsfehler

### ISSUE THREAD

**Issue by fkrb** [withanage/mpt#36]
Auszeichnungen

- Hochgestellung (Superscript), Jats: sup
- Tiefstellungen (Subscript), Jats: sub
- Durchstreichung (Strikethrough), Jats: strike

nicht unterstützt.

https://github.com/withanage/mpt/blob/master/static/tests/word/Superscript_Subscript_Strike.docx

**Comment by withanage** [comment]
@fkrb 
Beispiel Link 
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/reader/index/48/out.xml

Folgende commits  wurden dazu verwendet.
https://github.com/withanage/mpt/commit/9dd7b3ed4b0af8e985c80811192d8c407519a571
https://github.com/withanage/lens/commit/6cdf09848ef72a283a4cd7dba7b85dc062a91277
https://github.com/withanage/lens/commit/6cdf09848ef72a283a4cd7dba7b85dc062a91277
https://github.com/UB-Heidelberg/meTypeset/commit/fd0e71a0ec88e9fb56f4b299e0c1118e41d8e008
