### ISSUE TITLE
Tiefergestellte Zahlen

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#42]
<a href="https://github.com/ankosi"><img src="https://avatars.githubusercontent.com/u/11088169?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ankosi](https://github.com/ankosi)**
_Friday Aug 12, 2016 at 13:24 GMT_
_Originally opened as https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/65_

----

@withanage Bei der Konvertierung von Word in XML werden tiefergestellte Buchstaben nicht erkannt (im XML müsste dort ein <sub>-Tag erscheinen).

**Comment by withanage** [comment]
@ankosi 
Beispiel Link 
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/reader/index/48/out.xml

Folgende commits  wurden dazu verwendet.
https://github.com/withanage/mpt/commit/9dd7b3ed4b0af8e985c80811192d8c407519a571
https://github.com/withanage/lens/commit/6cdf09848ef72a283a4cd7dba7b85dc062a91277
https://github.com/withanage/lens/commit/6cdf09848ef72a283a4cd7dba7b85dc062a91277
https://github.com/UB-Heidelberg/meTypeset/commit/fd0e71a0ec88e9fb56f4b299e0c1118e41d8e008

**Comment by ankosi** [comment]
Im Beispiel-Link sind Wörter durchgestrichen (strikethrough). Gut, dass das jetzt möglich ist! In diesem Issue ging es aber um tiefergestellte Zeichen (<sub></sub>), wie z. B. in chemischen Formeln (CO<sub>2</sub>).

**Comment by withanage** [comment]
@ankosi   siehe torsi. war nicht im Beispiel
