### ISSUE TITLE
[mpdf]  Integration mit anderen Tools

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#5]
Hier soll  überprüft werden,  wie  die Anbindung 
als  Konsolentool
mit python
...

**Comment by kadowa** [comment]
Für Python gibt es eigene PDF-Generatoren. Hier ein paar, die wir testen könnten:

 [ ] [WeasyPrint|http://weasyprint.org/]
 [ ] [xhtml2pdf|http://www.xhtml2pdf.com/]
 [ ] [pdfkit|https://pypi.python.org/pypi/pdfkit]

**Comment by withanage** [comment]
mpdf besteht die allgemeine Anforderungen nicht. Wird nur zusätzlich angeboten.
