### ISSUE TITLE
[mpdf]   Die Abhängigkeit von externen Bibliotheken

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#6]

**Comment by kadowa** [comment]
Benötigt werden

```
php5-cli
php5-gd
```

\[[Quelle](http://sourcefabric.booktype.pro/booktype-20-for-authors-and-publishers/installing-a-pdf-renderer/)\]

**Comment by withanage** [comment]
Habe die wiki Seite angelegt. 
<url>itwiki/MPT
bitte eintragen. Falls auch noch eine minimale php version benötgit wird, kannst du auch aufnehmen.
