### ISSUE TITLE
[mpdf]  RightToLeft Sprachen 

### ISSUE THREAD

**Issue by withanage** [withanage/mpt#7]
Ob  die Sprachen R2L Sprachen unterstütz wird und ob man beide  (L2R  und R2L) mischen  kann,

**Comment by kadowa** [comment]
Vermutlich ja \[[Quelle](http://mpdf1.com/manual/index.php?tid=453)\]:

> mPDF recognises both Arabic and Hebrew languages and reverses text direction automatically.

Haben wir entsprechende Testdaten?

**Comment by withanage** [comment]
Nein. noch keine.
Ich würde eine minimalte Input  html Datei bauen umd mit mpdf konvertieren und in der Übersicht der Test-Ergebnisse aufnehmen.
<html dir="rtl"  lang="meine-sprache">
Die Seite hat  Blind-texte
http://generator.lorem-ipsum.info/_arabic
